# Generated by Django 2.0.2 on 2018-03-01 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='current_user', max_length=22)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.SmallIntegerField(default=1)),
                ('friends', models.SmallIntegerField(default=1)),
                ('expenses', models.SmallIntegerField(default=1)),
                ('searchable', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='first', max_length=25)),
                ('l_name', models.CharField(default='last', max_length=25)),
                ('bio', models.CharField(default='bio', max_length=220)),
                ('street', models.CharField(default='street address', max_length=200)),
                ('city', models.CharField(default='city', max_length=100)),
                ('state', localflavor.us.models.USStateField(default='CA', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default=12345, max_length=10)),
                ('phone', models.IntegerField(default='000-ooo-oooo')),
                ('dob', models.DateField(default='1950-01-01')),
                ('gender', models.CharField(default='Other', max_length=5)),
                ('lob', models.CharField(default='occupation', max_length=40)),
                ('dba', models.CharField(default='comapny', max_length=40)),
                ('account_type', models.CharField(default='INDIVIDUAL', max_length=20)),
                ('synapse_id', models.CharField(default='123456789', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='current_user', max_length=22)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requested', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(default='some action', max_length=200)),
                ('reference', models.IntegerField(default='101', null=True)),
                ('category', models.IntegerField(default=1)),
                ('status', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
